[package]
name = "egg_benchmark"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
criterion = "0.5.1"
egg = "0.9.5"
log = "0.4.21"
rand = "0.8.5"

[[bench]]
name = "benchmarks"
harness = false
